version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.13.0
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq

  db:
    image: postgres:16.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=companies_db

volumes:
  db-data:
  rabbitmq: