version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.13.0
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq

  db:
    image: postgres:16.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=companies_db
  
  ftp:
    image: garethflowers/ftp-server
    environment:
      - FTP_PASS=123
      - FTP_USER=user
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - ftp:/home/user


volumes:
  db-data:
  rabbitmq:
  ftp: